package:
  name: metaio
  version: '8.4.0_1'

source:
  url: http://software.ligo.org/lscsoft/source/metaio-8.4.0.tar.gz

build:
  detect_binary_files_with_prefix: true

about:
  home: 'https://www.lsc-group.phys.uwm.edu/daswg/docs/howto/lscsoft-install.html'
