package:
  name: lalsuite
  version: '6.37'

source:
  git_url: https://github.com/lscsoft/lalsuite.git

requirements:
  build:
    - python
    - numpy
    - h5py
    - scipy
    - cython
    - swig
    - gsl
    - libframe
    - metaio

  run:
    - python
    - numpy
    - h5py
    - scipy
    - cython
    - swig
    - gsl
    - libframe
    - metaio

build:
  detect_binary_files_with_prefix: true

about:
  home: 'https://www.lsc-group.phys.uwm.edu/daswg/docs/howto/lscsoft-install.html'
